name: GitHub Actions Lab

on:
  workflow_dispatch:

jobs:
  workspace-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Create a text file
        run: echo "This file is inside the workspace" > demo.txt

      - name: Display file content
        run: cat demo.txt
